@extends('base')

@section('title', 'RC Tech Web')
@section('meta', 'Développeur web, je crée des sites modernes et performants sur mesure pour répondre à vos besoins numériques. Sites vitrines, e-commerce et plus.')
@section('hero-banner', asset('css/include/hero-banner/style.css'))
@section('service', asset('css/include/service/style.css'))
@section('contact', asset('css/include/contact/style.css'))
@section('propos', asset('css/include/propos/style.css'))
@section('realisation', asset('css/include/realisation/style.css'))
@section('realisationJs', asset('js/realisation/script.js'))
@section('content')
@include('include.hero-banner.hero-banner')
@include('include.propos.propos')
@include('include.realisation.realisation')
@include('include.service.service')
@include('include.contact.contact')
@endsection